[32m2024-04-04 18:52:37 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 8dfde504-3433-4025-aa49-57b28a456a45 - 24259 - LOGS_CAPTURED - Started capturing logs in process (pid: 24259).
[32m2024-04-04 18:52:37 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 8dfde504-3433-4025-aa49-57b28a456a45 - 24259 - training_data - STEP_START - Started execution of step "training_data".
[32m2024-04-04 18:52:37 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 8dfde504-3433-4025-aa49-57b28a456a45 - 24259 - training_data - STEP_OUTPUT - Yielded output "result" of type "Nothing". Warning! Type check failed.
[32m2024-04-04 18:52:37 -0500[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 8dfde504-3433-4025-aa49-57b28a456a45 - 24259 - training_data - STEP_FAILURE - Execution of step "training_data" failed.

dagster._core.errors.DagsterTypeCheckDidNotPass: Type check failed for step output "result" - expected type "Nothing". Description: Value must be None, got a <class 'pandas.core.frame.DataFrame'>

Stack Trace:
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_plan.py", line 282, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 528, in core_dagster_event_sequence_for_step
    for evt in _type_check_and_store_output(step_context, user_event):
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 580, in _type_check_and_store_output
    for output_event in _type_check_output(step_context, step_output_handle, output, version):
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 448, in _type_check_output
    raise DagsterTypeCheckDidNotPass(
[0m
