[32m2024-04-24 17:35:05 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 605ac9f6-171d-4171-a494-2d875950fe44 - 16685 - LOGS_CAPTURED - Started capturing logs in process (pid: 16685).
[32m2024-04-24 17:35:05 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 605ac9f6-171d-4171-a494-2d875950fe44 - 16685 - splitWomanAndChildrenFromMen - STEP_START - Started execution of step "splitWomanAndChildrenFromMen".
[32m2024-04-24 17:35:05 -0500[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 605ac9f6-171d-4171-a494-2d875950fe44 - 16685 - splitWomanAndChildrenFromMen - STEP_FAILURE - Execution of step "splitWomanAndChildrenFromMen" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "splitWomanAndChildrenFromMen"::

ValueError: The number of FixedLocator locations (1), usually from a call to set_ticks, does not match the number of labels (2).

Stack Trace:
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 464, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fussy/Desktop/317_Project_1/src/assets.py", line 124, in splitWomanAndChildrenFromMen
    plt.xticks([pos + bar_width / 2 for pos in positions_adults], ['Total Passengers', 'Survivors'])
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/matplotlib/pyplot.py", line 2068, in xticks
    labels_out = ax.set_xticklabels(labels, minor=minor, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/matplotlib/axes/_base.py", line 73, in wrapper
    return get_method(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/matplotlib/_api/deprecation.py", line 297, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fussy/miniconda3/envs/dag/lib/python3.12/site-packages/matplotlib/axis.py", line 2025, in set_ticklabels
    raise ValueError(
[0m
