[32m2024-04-24 23:20:57 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 4eb6bf00-218a-4f46-975a-5da37f385b68 - 42497 - LOGS_CAPTURED - Started capturing logs in process (pid: 42497).
[32m2024-04-24 23:20:57 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 4eb6bf00-218a-4f46-975a-5da37f385b68 - 42497 - remove_NA - STEP_START - Started execution of step "remove_NA".
[32m2024-04-24 23:20:57 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 4eb6bf00-218a-4f46-975a-5da37f385b68 - 42497 - remove_NA - STEP_OUTPUT - Yielded output "result" of type "Nothing". Warning! Type check failed.
[32m2024-04-24 23:20:57 -0500[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 4eb6bf00-218a-4f46-975a-5da37f385b68 - 42497 - remove_NA - STEP_FAILURE - Execution of step "remove_NA" failed.

dagster._core.errors.DagsterTypeCheckDidNotPass: Type check failed for step output "result" - expected type "Nothing". Description: Value must be None, got a <class 'pandas.core.frame.DataFrame'>

Stack Trace:
  File "/Users/qingtan/anaconda3/envs/cse217a/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_plan.py", line 282, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/Users/qingtan/anaconda3/envs/cse217a/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 528, in core_dagster_event_sequence_for_step
    for evt in _type_check_and_store_output(step_context, user_event):
  File "/Users/qingtan/anaconda3/envs/cse217a/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 580, in _type_check_and_store_output
    for output_event in _type_check_output(step_context, step_output_handle, output, version):
  File "/Users/qingtan/anaconda3/envs/cse217a/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 448, in _type_check_output
    raise DagsterTypeCheckDidNotPass(
[0m
