[32m2024-04-24 23:22:54 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 846e8ed8-8614-4bea-8f31-a84f61570a63 - 42920 - LOGS_CAPTURED - Started capturing logs in process (pid: 42920).
[32m2024-04-24 23:22:54 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 846e8ed8-8614-4bea-8f31-a84f61570a63 - 42920 - remove_NA - STEP_START - Started execution of step "remove_NA".
[32m2024-04-24 23:22:54 -0500[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 846e8ed8-8614-4bea-8f31-a84f61570a63 - 42920 - remove_NA - STEP_FAILURE - Execution of step "remove_NA" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "remove_NA"::

TypeError: unhashable type: 'DataFrame'

Stack Trace:
  File "/Users/qingtan/anaconda3/envs/cse217a/lib/python3.10/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/qingtan/anaconda3/envs/cse217a/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 464, in iterate_with_context
    next_output = next(iterator)
  File "/Users/qingtan/anaconda3/envs/cse217a/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/Users/qingtan/anaconda3/envs/cse217a/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/Users/qingtan/Desktop/CSE314A/314_Project_1/src/assets.py", line 11, in remove_NA
    return MaterializeResult(metadata={data})
[0m
